collections:
  - name: "terminal" # 用于路由，例如，/admin/collections/blog
    label: "terminal" # 在 UI 中使用
    folder: "src/content/blog" # 存储文档的文件夹路径
    create: true # 允许用户在此集合中创建新文档
    fields: # 每个文档的字段，通常在 front matter 中
      - { label: "布局", name: "layout", widget: "hidden", default: "blog" }
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "缩略图", name: "thumbnail", widget: "image" }
      - { label: "评分（1-5 的范围）", name: "rating", widget: "number" }
      - { label: "正文", name: "body", widget: "markdown" }
media_folder: "src/assets/images" # 文件将被存储在仓库中的位置
public_folder: "src/assets/images" # 上传媒体文件的 src 属性
backend:
  name: github
  repo: "YumeHinata/AstroBlog"
  branch: "main"
  api_root: "https://api.github.com"
  # site_domain: "location.hostname"
  base_url: "https://astro.yum9.in"
  auth_endpoint: "/auth"