collections:
  - name: "terminal" # 用于路由，例如，/admin/collections/blog
    label: "paper" # 在 UI 中使用
    folder: "src/content/posts" # 存储文档的文件夹路径
    create: true # 允许用户在此集合中创建新文档
    fields: # 每个文档的字段，通常在 front matter 中
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "published", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "描述", name: "description", widget: "text", required: false }
      - { label: "封面图片", name: "image", widget: "image", default: "https://rdimg.yumehinata.com/random-wallpaper"}
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "category", widget: "string", required: false }
      - { label: "草稿状态", name: "draft", widget: "boolean", default: false }
      - { label: "正文", name: "body", widget: "markdown" }
media_folder: "./images" # 文件将被存储在仓库中的位置
public_folder: "./images" # 上传媒体文件的 src 属性
backend:
  name: github
  repo: "YumeHinata/AstroBlog"
  branch: "main"
  api_root: "https://api.github.com"
  site_url: "https://www.yumehinata.com"
  base_url: "https://www.yumehinata.com"
  auth_endpoint: "auth"